/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import Logica.ControladorLogica_Lista;
import Logica.ListaTareas;
import javax.swing.JOptionPane;
/**
 *
 * @author Itati
 */
public class ToDoList extends javax.swing.JFrame {
    
    ControladorLogica_Lista ctrlLogLis = new ControladorLogica_Lista();
    ListaTareas tare = new ListaTareas();
    DefaultTableModel tabla =new DefaultTableModel(){
    };
    
    /**
     * Creates new form ToDoList
     */
    public ToDoList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_ver = new javax.swing.JTable();
        jBttn_crear = new javax.swing.JButton();
        jtxt_descripcion = new javax.swing.JTextField();
        jtxt_titulo = new javax.swing.JTextField();
        jCBX_estado = new javax.swing.JComboBox<>();
        jbttn_actualizar = new javax.swing.JButton();
        lbl_buscar = new javax.swing.JLabel();
        jbttn_Eliminar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_filtro1 = new javax.swing.JLabel();
        jbttn_mostrar = new javax.swing.JButton();
        jbttn_buscar = new javax.swing.JButton();
        jbttn_filtrar = new javax.swing.JButton();
        Cbox_filtro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("A little sunshine", 1, 18)); // NOI18N

        lbl_titulo.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("LISTA DE TAREAS");

        jtbl_ver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Descripcion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_ver.setCellSelectionEnabled(true);
        jtbl_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_verMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_ver);

        jBttn_crear.setText("Crear Tarea");
        jBttn_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBttn_crearMouseClicked(evt);
            }
        });

        jtxt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_descripcionKeyTyped(evt);
            }
        });

        jtxt_titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_tituloKeyTyped(evt);
            }
        });

        jCBX_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completada", "No Completada" }));
        jCBX_estado.setSelectedItem("Elija una opcion");

        jbttn_actualizar.setText("Actualizar Tarea");
        jbttn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttn_actualizarMouseClicked(evt);
            }
        });

        lbl_buscar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buscar.setText("BUSCADOR:");

        jbttn_Eliminar.setText("Eliminar Tarea");
        jbttn_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttn_EliminarMouseClicked(evt);
            }
        });

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Estado");

        lbl_filtro1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_filtro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_filtro1.setText("FILTRO: ");

        jbttn_mostrar.setText("Mostrar tareas");
        jbttn_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttn_mostrarMouseClicked(evt);
            }
        });

        jbttn_buscar.setText("...");
        jbttn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttn_buscarMouseClicked(evt);
            }
        });

        jbttn_filtrar.setText("...");
        jbttn_filtrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttn_filtrarMouseClicked(evt);
            }
        });

        Cbox_filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Completada", "No Completada" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbttn_actualizar)
                                .addGap(43, 43, 43)
                                .addComponent(jbttn_Eliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_filtro1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbox_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn_filtrar)
                                .addGap(104, 104, 104)
                                .addComponent(lbl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn_buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBX_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxt_descripcion)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(57, 57, 57)
                                                        .addComponent(jLabel3))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(38, 38, 38)
                                                        .addComponent(jLabel2)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jtxt_titulo, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbttn_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(jBttn_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(38, 38, 38)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_filtro1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn_filtrar)
                            .addComponent(Cbox_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbttn_actualizar)
                            .addComponent(jbttn_Eliminar))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBX_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBttn_crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn_mostrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttn_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttn_mostrarMouseClicked
        tabla.setRowCount(0);
        DefaultTableModel tabla =new DefaultTableModel() {
          
            //ESTABLECER QUE LAS FILAS Y LAS COLUMNAS NO SEAN EDITABLES
            @Override
            public boolean isCellEditable(int row, int colum){
                return false;
            }
        };
        

               String titulos [] = {"ID", "Titulo", "Descripción", "Estado"};
        
                tabla.setColumnIdentifiers(titulos);
            
        
 
        List <ListaTareas> listaTarea = ctrlLogLis.MostrarDatos();
        
        //RECORRER LA LISTA Y MOSTRAR CADA UNO DE LOS ELEMENTOS EN LA TABLA
        if(listaTarea!= null){
            for (ListaTareas tare : listaTarea){
                Object [] objeto = {
                tare.getId(),
                tare.getTitulo(),
                tare.getDescripcion(),
                tare.getEstado()};
                
                tabla.addRow(objeto);
            }
        }
        
        jtbl_ver.setModel(tabla);
        
        
    }//GEN-LAST:event_jbttn_mostrarMouseClicked

    private void jBttn_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBttn_crearMouseClicked
            String creartitulo = jtxt_titulo.getText();
  
             List<ListaTareas> tarea = ctrlLogLis.ConsultarTarea();

              if(jtxt_titulo.getText().isEmpty() || jtxt_descripcion.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "El titulo o descripcion de la tarea esta vacio, por favor ingrese un titulo o una descripcion");
              }else{
              String titulo = jtxt_titulo.getText();
            String Descripcion = jtxt_descripcion.getText();
            String Estado = (String) jCBX_estado.getSelectedItem();


            tare.setTitulo(titulo);
            tare.setDescripcion(Descripcion);
            tare.setEstado(Estado);

            ctrlLogLis.CrearTarea(tare);
            JOptionPane.showMessageDialog(rootPane, "La Tarea fue creada correctamente");
             }
            
    }//GEN-LAST:event_jBttn_crearMouseClicked

    private void jbttn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttn_actualizarMouseClicked
         
        List<ListaTareas> tare = ctrlLogLis.ConsultarTarea();
            for (ListaTareas tarea : tare) {
                if (tarea.getTitulo().equals(jtxt_titulo.getText())) {
                    tarea.setDescripcion(jtxt_descripcion.getText());
                    tarea.setEstado(String.valueOf(jCBX_estado.getSelectedItem()));
                } 
                ctrlLogLis.ActualizarTarea(tarea);
             
            } 
            JOptionPane.showMessageDialog(rootPane, "La Tarea se actualizo correctamente");
              
    }//GEN-LAST:event_jbttn_actualizarMouseClicked

    private void jbttn_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttn_EliminarMouseClicked
        
        List<ListaTareas> tarea = ctrlLogLis.ConsultarTarea();
            for (ListaTareas tare : tarea) {
                if (tare.getTitulo().equals(txt_buscar.getText())) {
                ctrlLogLis.EliminarTarea(buscarId(tare.getTitulo()));
                }
            }
            
        JOptionPane.showMessageDialog(rootPane, "La Tarea fue eliminada correctamente");
         
    }//GEN-LAST:event_jbttn_EliminarMouseClicked

    private void jbttn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttn_buscarMouseClicked
        tabla.setRowCount(0);
        String buscar = txt_buscar.getText();
        
        List<ListaTareas> tarea = ctrlLogLis.ConsultarTarea();
            
        //ESTABLECER LOS TITULOS
               String titulos [] = {"ID", "Titulo", "Descripción", "Estado"};
        
                tabla.setColumnIdentifiers(titulos);
         
        List <ListaTareas> listaTarea = ctrlLogLis.MostrarDatos();
        
        if(listaTarea!= null){
            for (ListaTareas tare : listaTarea){
                if (tare.getTitulo().equalsIgnoreCase(buscar)) {
                Object [] objeto = {
                tare.getId(),
                tare.getTitulo(),
                tare.getDescripcion(),
                tare.getEstado()};
                
                tabla.addRow(objeto);
                }
            }
           
        }
        
        jtbl_ver.setModel(tabla);
        tabla.fireTableDataChanged();
        
    }//GEN-LAST:event_jbttn_buscarMouseClicked

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
       int key = evt.getKeyChar();
        boolean Letras = ((key >= 65 && key <= 90) || (key >= 97 && key <= 122) || (key == 32));  
        
        if (!Letras)
          {  evt.consume();  }
        
        if(txt_buscar.getText().length() >= 25){
            evt.consume();
        }
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void jtxt_tituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_tituloKeyTyped
        int key = evt.getKeyChar();
        boolean Letras = ((key >= 65 && key <= 90) || (key >= 97 && key <= 122) || (key == 32));  
        
        if (!Letras)
          {  evt.consume();  }
       
        if(jtxt_titulo.getText().length() >= 25){
            evt.consume();
        }
    
    }//GEN-LAST:event_jtxt_tituloKeyTyped

    private void jtxt_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_descripcionKeyTyped
       int key = evt.getKeyChar();
        boolean Letras = ((key >= 65 && key <= 90) || (key >= 97 && key <= 122) || (key == 32));  
        
        if (!Letras)
          {  evt.consume();  }
         if(jtxt_descripcion.getText().length() >= 40){
            evt.consume();
        }
    }//GEN-LAST:event_jtxt_descripcionKeyTyped

    private void jbttn_filtrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttn_filtrarMouseClicked
       tabla.setRowCount(0);
       String filtro = String.valueOf(Cbox_filtro.getSelectedItem());
       
        // ESTABLECER LOS TITULOS Y EL RESTO DEL FORMATO DE LA TABLA
        String titulos[] = {"ID", "Titulo", "Descripción", "Estado"};
        tabla.setColumnIdentifiers(titulos);

        List<ListaTareas> listaTarea = ctrlLogLis.MostrarDatos();

        if (listaTarea != null) {
            for (ListaTareas tare : listaTarea) {
                // Utiliza equalsIgnoreCase para comparar ignorando mayúsculas/minúsculas
                if (tare.getEstado().equals(filtro)) {
                    Object[] objeto = {
                            tare.getId(),
                            tare.getTitulo(),
                            tare.getDescripcion(),
                            tare.getEstado()
                    };

                    tabla.addRow(objeto);
                } 
                
            }
            
        }
        jtbl_ver.setModel(tabla);
        
    }//GEN-LAST:event_jbttn_filtrarMouseClicked

    private void jtbl_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_verMouseClicked
        int seleccion = jtbl_ver.getSelectedRow();
        jtxt_titulo.setText(String.valueOf(jtbl_ver.getValueAt(seleccion, 1)));
        jtxt_descripcion.setText(String.valueOf(jtbl_ver.getValueAt(seleccion, 2)));
        jCBX_estado.setSelectedItem(String.valueOf(jtbl_ver.getValueAt(seleccion, 3)));
    }//GEN-LAST:event_jtbl_verMouseClicked
    
    public int buscarId(String titulo) {
        
       int count = 0;
       List<ListaTareas> tareas = ctrlLogLis.ConsultarTarea();
       for (ListaTareas tare : tareas) {
           if (tare.getTitulo().equals(titulo)) {
                return count = tare.getId();
           }
       }
        return count;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ToDoList().setVisible(true);
//            }
//        });
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbox_filtro;
    private javax.swing.JButton jBttn_crear;
    private javax.swing.JComboBox<String> jCBX_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbttn_Eliminar;
    private javax.swing.JButton jbttn_actualizar;
    private javax.swing.JButton jbttn_buscar;
    private javax.swing.JButton jbttn_filtrar;
    private javax.swing.JButton jbttn_mostrar;
    private javax.swing.JTable jtbl_ver;
    private javax.swing.JTextField jtxt_descripcion;
    private javax.swing.JTextField jtxt_titulo;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_filtro1;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}

